name: Publish Book to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Install mdBook if it is not already installed.
      # You may need to specify a version.
      - name: Install mdBook
        run: |
          wget -qO- https://github.com/rust-lang/mdBook/releases/download/v0.4.7/mdbook-v0.4.7-x86_64-unknown-linux-gnu.tar.gz | tar xvz
          sudo mv mdbook /usr/local/bin

      - name: Build Book
        run: |
          mdbook build docs/book

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book  # Set this to the path where mdBook outputs the HTML files
